### ISSUE TITLE
封面的学院

### ISSUE THREAD

**Issue by Joe-qa** [MGG1996/DissertationUESTC#1]
有些学院的名称一行放不下，比如计算机学院和集电的全称都很长，一行放不下，目前模板会造成字覆盖，应该是需要换行，大佬可以对这块加一个小的修改

**Comment by MGG1996** [comment]
你使用的是什么文献类型，学院全称是什么。

我并未在规范里看到这部分内容可以换行的说明，目前你可以先试试使用scalebox来调整学院的字宽，将之缩放到合适长度。这一技巧在官方提供的专业学位封面示例中有所体现。

**Comment by MGG1996** [comment]
请提供一下你使用的文档类型和对应的学院全称

**Comment by Joe-qa** [comment]
专业硕士，计算机科学与工程学院（网络空间安全学院）

**Comment by MGG1996** [comment]
正常来说，从学校官方提供的规范来看，这部分内容已经顶到封面页的下边线，应该不允许换行了，我也的确没在规范中看到这里可以换行的说明。

你这个问题可以尝试用scalebox曲线解决一下，适当压缩这部分字宽。这一设计技巧在学校官方提供的专业学位封面上有所体现。比如其中“专业学位类别”就是如此产生的。

**Comment by Joe-qa** [comment]
好的，我试一下，谢谢大佬

**Comment by MGG1996** [comment]
![image](https://github.com/user-attachments/assets/08183956-582c-479f-9b5e-1fd81611400a)
上图是我按给你的建议尝试的结果，对应源码为\scalebox{0.66}[1.0]{计算机科学与工程学院（网络空间安全学院）}。
很显然，你还可以适当放大0.66这个参数，让他产生更合理的缩放。

**Comment by Joe-qa** [comment]
ok,感谢~

**Comment by MGG1996** [comment]
多说一句，在设计模板的时候，0.66这个参数是我经过尝试后能与官方的word封面保持相同缩小后字宽的结果。当前这种状态，在我个人看来，还比较协调。

如果可以的话，你可以看看你往届师兄师姐最后交上去的版本长什么样子。如果他们换了行，那截一张完整的封面图到这里来，我看看能不能复刻。

**Comment by Joe-qa** [comment]
今年是官网修改了计算机学院的这个全称，以前我师兄他们都是不带括号里的内容的，所以以前是可以放的下的

**Comment by MGG1996** [comment]
那这样的话，我个人看法是如果官方没有更新对应的学位论文封面，那先采用我上面建议的方法。这里如果强行换行，页面下边界会非常窄，十分不协调。

中文学院名改了的话，那你们英文学院名改了没。在扉页里，英文学院是可以换行的，但是，目前至多能两行，看你们改完之后这个架势，两行我感觉都不太够用，哈哈哈哈。

**Comment by Joe-qa** [comment]
英文也相应改了，英文换行是两行（不过感觉也很挤，哈哈哈）中文的先按你说的办法吧，中文这块两行确实和下面边距太小了

**Comment by MGG1996** [comment]
那还可以，哈哈哈哈

**Comment by MGG1996** [comment]
在刚刚发布的v24.12.10版本中，模板将自动调整封面页中过长学院名称的字宽，使之与下划线相适应，无需用户再手动调整。目前的方式相对来说能更好地保证同学院论文封面的一致性。

**Comment by Joe-qa** [comment]
![image](https://github.com/user-attachments/assets/2b97f4bd-6ac3-4d09-8019-ea2259640047)
找到了之前的一个师兄的封面这里是换行的，之前看到的同届的另一个师兄是直接没写括号里的内容。。。。。看来学校对这里要求不是很严

**Comment by MGG1996** [comment]
这张图能不能截全我看一下，你可以隐去其他能看到个人信息的东西。主要是看看这地方离边界有多远，这可能还涉及到本科论文的封面，他们的学院是在最上面的。

**Comment by Joe-qa** [comment]
![a4ef475d2cd90df1507928b8d72701f](https://github.com/user-attachments/assets/dac7cacf-31fe-4b99-bcda-1df86d980409)
zhey这样的

**Comment by MGG1996** [comment]
已更新v24.12.10版本，该版本修改了`\uestccover`命令的使用方式。现在用户可自行决定使用缩放还是换行，但，换行必定会改变封面结构，这无可避免。
