### ISSUE TITLE
缩略词表可以像王稳学长那样实现吗？

### ISSUE THREAD

**Issue by xlshan666** [MGG1996/DissertationUESTC#3]

**Comment by xlshan666** [comment]
试了一下现在的缩略词表，不是那么的方便，王稳学长的

**Comment by MGG1996** [comment]
目前不行，我们使用的是不同的宏包。旧模板中的方式主要优势是你可以随意创建所有缩略词条目，然后后续被引用的才会出现在文档中。

从习惯上来说，既然都要引用了，那和手敲缩略词也差别不大。但是现在需要作者在第一次解释名词时添加对应的缩略词条目，当然还不能把未用的缩略词写进去。

另外，旧模板里，缩略词这部分似乎不会换行。我见过很多论文缩略词的中文解释都顶到了页眉线以外，个人觉得这种排版结果并不符合要求。

个人精力有限，像这类个人使用习惯的问题，我目前没有打算维护，不好意思。

**Comment by xlshan666** [comment]
好的，谢谢您。确实，我在硕士论文使用旧版的缩略词是也发现了换行的问题。早晨实践了一下您的版本的缩略词，我运行还是有点问题，我再试一下

**Comment by MGG1996** [comment]
具体现象方便的话可以截图来看看

**Comment by MGG1996** [comment]
你命令用错了，自信看readme，模板提供的命令应该是`\nomchn{}{}{}`。

**Comment by xlshan666** [comment]
sorry, 现在OK了，谢谢您
