### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by Joe-qa** [MGG1996/DissertationUESTC#4]
![image](https://github.com/user-attachments/assets/d027b71d-8508-4aa4-b9f0-1fcf3d7222f9)
发现l了一个奇怪的点，就是参考文献过多的时候，比如图中所示第82个参考文献显示为斜体，这是因为参考文献限制个数吗

**Comment by MGG1996** [comment]
模板当然不会设置这种不合理的限制。

从你截图的结果来看，显然真正导致问题的是你的第81条参考文献。如果我没记错，如你显示的`LaTeX`需要使用命令生成，这条命令的影响范围很可能比你自己以为的大。如果你一定要用这种LaTeX独特的样式，你至少应该在bib数据库里面将相关命令用`{}`括起来。
